# Functions for data collection and analysis

#Retrieve dataset citations generated by DataOne metrics service (from Jeanette Clark):
metrics_citations <- function(from = as.POSIXct("2010-01-01"), to = as.POSIXct(Sys.Date())){
  
  from <- as.Date(from); to <- as.Date(to)
  from_q <- paste(stringr::str_pad(lubridate::month(from), 2, side = "left", pad = "0"),
                  stringr::str_pad(lubridate::day(from), 2, side = "left", pad = "0"),
                  stringr::str_pad(lubridate::year(from), 2, side = "left", pad = "0"),
                  sep = "/")
  
  to_q <- paste(stringr::str_pad(lubridate::month(to), 2, side = "left", pad = "0"),
                stringr::str_pad(lubridate::day(to), 2, side = "left", pad = "0"),
                stringr::str_pad(lubridate::year(to), 2, side = "left", pad = "0"),
                sep = "/")
  
  d <- jsonlite::fromJSON(paste0('https://logproc-stage-ucsb-1.test.dataone.org/metrics?q={%22metricsPage%22:{%22total%22:0,%22start%22:0,%22count%22:0},%22metrics%22:[%22citations%22],%22filterBy%22:[{%22filterType%22:%22repository%22,%22values%22:[%22urn:node:ARCTIC%22],%22interpretAs%22:%22list%22},{%22filterType%22:%22month%22,%22values%22:[%22', from_q,'%22,%22', to_q, '%22],%22interpretAs%22:%22range%22}],%22groupBy%22:[%22month%22]}'))
  
  output_json <- d$resultDetails$citations # pulls citation info
  output_df <- as.data.frame(do.call(rbind, output_json), row.names = FALSE) # binds nested cit info into dataframe
  # output_clean <- rownames_to_column(output_df, var = "citation_id") # converts row names to column
  return(output_df)
}

# read in raw scythe results .csvs into a list of dataframes
mk_result_list <- function(asource){
  path <- eval(parse(text = paste0("path_", asource)))
  if(file.exists(path)){
    assign(paste0("cits_",asource), read_csv(file.path(path)))
  }
}

# pull dataframe rows that had API request errors
did_this_error <- function(adf){
  error_index <- is.na(adf$article_id)
  adf[error_index, "dataset_id"]
}

# run error DOIs back through scythe
query_errors <- function(adf, asource){
  if(nrow(adf) > 0){
    keyring::keyring_unlock("scythe", key)
    scythe::citation_search(adf$dataset_id, asource)
  } 
} 

# write error re-run results to .csv
write_error_results <- function(adf, asource){
  if(!is.null(adf)) {
    write.csv(adf, paste0(path_error, asource, "_err_res.csv"), row.names = F)
  }}

# function to calculate percent of source citations also found in a second source
calc_prct_overlap <- function(source_1, source_2) {
  pairs <-
    inner_join(source_1, source_2, by = c("article_id", "dataset_id"))
  overlap <-
    (nrow(pairs) / nrow(source_1)) # percent of source_1 total also found in source_2 (pairs)
  return(overlap)
}